# Generated by Django 5.2.15 on 2026-07-02 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_to_zwl', models.FloatField(default=25.0)),
                ('source', models.CharField(default='manual', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PackageDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField(default=0)),
                ('width', models.FloatField(default=0)),
                ('height', models.FloatField(default=0)),
                ('weight', models.FloatField(default=0)),
                ('dimensional_factor', models.IntegerField(default=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('is_pay_forward', models.BooleanField(default=False)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('ecocash', 'EcoCash')], default='cash', max_length=20)),
                ('currency', models.CharField(choices=[('usd', 'USD'), ('zwl', 'ZWL')], default='usd', max_length=10)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=64, unique=True)),
                ('method', models.CharField(max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.FloatField(default=0)),
                ('currency', models.CharField(default='usd', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimensional_factor', models.IntegerField(default=5000)),
                ('base_fee', models.FloatField(default=2)),
                ('insurance_fee', models.FloatField(default=1)),
                ('rate_per_kg', models.FloatField(default=0.5)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('sent_from_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_sent_from_shop', to='users.branch')),
                ('sent_to_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_sent_to_shop', to='users.branch')),
            ],
        ),
        migrations.CreateModel(
            name='PrePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, max_length=250)),
                ('creation_code', models.CharField(max_length=20)),
                ('self_created', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='users.customer')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='users.customer')),
                ('to_shop', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='to_shop', to='users.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, max_length=250)),
                ('receiver_code', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('is_collected', models.BooleanField(default=False)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='intercity.batch')),
                ('logged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logged_by', to=settings.AUTH_USER_MODEL)),
                ('dimensions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intercity.packagedimension')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intercity.payment')),
                ('pre_package', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='intercity.prepackage')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intercity.price'),
        ),
    ]
