
services:
  backend:
    build: ./backend
    container_name: movo_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DEBUG: "1"
      DB_NAME: movo_db
      DB_USER: movo_user
      DB_PASSWORD: movo_password
      DB_HOST: db
      DB_PORT: "5432"
      CHANNEL_REDIS_HOST: "redis-16444.c282.east-us-mz.azure.cloud.redislabs.com"
      CHANNEL_REDIS_PORT: "16444"
      CHANNEL_REDIS_SOCKET_TIMEOUT: "60"
      CHANNEL_REDIS_SOCKET_CONNECT_TIMEOUT: "60"
      CHANNEL_REDIS_HEALTH_CHECK_INTERVAL: "30"
      CHANNEL_REDIS_RETRY_ON_TIMEOUT: "1"
      CHANNEL_REDIS_USE_SSL: "1"
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_healthy

  db:
    image: postgres:15
    container_name: movo_db
    environment:
      POSTGRES_USER: movo_user
      POSTGRES_PASSWORD: movo_password
      POSTGRES_DB: movo_db
    ports:
      - "${POSTGRES_HOST_PORT:-5433}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:7-alpine
    container_name: movo_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  postgres_data:
