# Generated by Django 5.2.17 on 2026-09-13 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_notificationoutbox'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='devicetoken',
            new_name='notificatio_user_id_40dfbf_idx',
            old_name='notificatio_user_id_0694a1_idx',
        ),
    ]
