# Generated by Django 5.2.16 on 2026-07-17 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suburb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('x_pos', models.DecimalField(decimal_places=3, max_digits=10)),
                ('y_pos', models.DecimalField(decimal_places=3, max_digits=10)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suburbs', to='users.city')),
            ],
            options={
                'ordering': ['city_id', 'name'],
                'constraints': [models.UniqueConstraint(fields=('city', 'name'), name='uniq_suburb_name_per_city')],
            },
        ),
    ]
