# Generated by Django 5.2.17 on 2026-08-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_suburb'),
    ]

    operations = [
        migrations.AddField(
            model_name='suburb',
            name='x_coord',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='suburb',
            name='y_coord',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='suburb',
            name='x_pos',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='suburb',
            name='y_pos',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
