# Generated by Django 5.2.17 on 2026-09-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_suburb_x_coord_suburb_y_coord_alter_suburb_x_pos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suburb',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
