# Generated by Django 5.2.17 on 2026-09-08 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_suburb_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suburb',
            name='x_pos',
        ),
        migrations.RemoveField(
            model_name='suburb',
            name='y_pos',
        ),
    ]
