# Generated by Django 5.2.17 on 2026-09-17 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_suburb_x_pos_remove_suburb_y_pos'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuburbAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100)),
                ('suburb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='users.suburb')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('suburb', 'alias'), name='uniq_suburb_alias_per_suburb')],
            },
        ),
    ]
