# Generated by Django 5.2.17 on 2026-10-02 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_biker_branch_contact_address_licence_nextofkin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='users.city'),
        ),
    ]
