# Generated by Django 5.2.17 on 2026-08-31 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "users",
            "0003_suburb_x_coord_suburb_y_coord_alter_suburb_x_pos_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="BikerDailySession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "biker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_sessions",
                        to="users.biker",
                    ),
                ),
            ],
            options={
                "unique_together": {("biker", "date")},
            },
        ),
    ]
