# Generated by Django 5.2.15 on 2026-07-02 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intracity', '0002_invoice_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='payment_method',
        ),
    ]
