# Generated by Django 5.2.16 on 2026-07-17 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0002_exchangerate'),
        ('intracity', '0004_suburbsearchlog'),
        ('users', '0002_suburb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='dropoff_location',
            new_name='dropoff_address',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='pickup_location',
            new_name='pickup_address',
        ),
        migrations.AddField(
            model_name='invoice',
            name='exchange_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookkeeping.exchangerate'),
        ),
        migrations.AddField(
            model_name='package',
            name='dropoff_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dropoff_area', to='users.suburb'),
        ),
        migrations.AddField(
            model_name='package',
            name='pickup_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_area', to='users.suburb'),
        ),
    ]
