# Generated by Django 5.2.16 on 2026-07-23 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intracity', '0005_rename_dropoff_location_package_dropoff_address_and_more'),
        ('users', '0002_suburb'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Ecocash', 'Ecocash'), ('Cash', 'Cash')], default='Cash', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='packagestatus',
            name='comments',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='EcocashPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('client_correlator', models.CharField(blank=True, max_length=100, null=True)),
                ('request_response', models.JSONField(blank=True, null=True)),
                ('provider_response', models.JSONField(blank=True, null=True)),
                ('is_successful', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intracity.invoice')),
            ],
        ),
    ]
