# Generated by Django 5.2.16 on 2026-08-04 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intracity', '0006_invoice_payment_method_packagestatus_comments_and_more'),
        ('users', '0002_suburb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Ecocash', 'Ecocash'), ('Cash', 'Cash'), ('PaynowEcocash', 'PaynowEcocash')], default='Cash', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='PaynowPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('poll_url', models.URLField(blank=True, null=True)),
                ('is_successful', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intracity.invoice')),
            ],
        ),
    ]
