# Generated by Django 5.2.17 on 2026-09-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intracity', '0007_alter_invoice_payment_method_paynowpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagestatus',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
