# Generated by Django 5.2.17 on 2026-09-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intracity', '0008_alter_packagestatus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
