# Generated by Django 6.0.6 on 2026-06-09 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField(default=0)),
                ('width', models.FloatField(default=0)),
                ('height', models.FloatField(default=0)),
                ('weight', models.FloatField(default=0)),
                ('dimensional_factor', models.IntegerField(default=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('is_pay_forward', models.BooleanField(default=False)),
                ('method', models.CharField(max_length=20)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimensional_factor', models.IntegerField(default=5000)),
                ('base_fee', models.FloatField(default=2)),
                ('rate_per_kg', models.FloatField(default=0.5)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('sent_from_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_shop', to='users.branch')),
                ('sent_to_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_shop', to='users.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, max_length=250)),
                ('receiver_code', models.CharField(max_length=20)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('is_collected', models.BooleanField(default=False)),
                ('collected_at', models.DateTimeField(blank=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='packages.batch')),
                ('logged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logged_by', to='users.staff')),
                ('sent_from_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_from_shop', to='users.branch')),
                ('sent_to_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_to_shop', to='users.branch')),
                ('dimensions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.packagedimension')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.payment')),
            ],
        ),
        migrations.CreateModel(
            name='PrePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, max_length=250)),
                ('creation_code', models.CharField(max_length=20)),
                ('self_created', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='users.customer')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='users.customer')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.price'),
        ),
    ]
