# Generated by Django 6.0.6 on 2026-06-09 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
        ('users', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='pre_package',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='packages.prepackage'),
        ),
        migrations.AddField(
            model_name='prepackage',
            name='to_shop',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='to_shop', to='users.branch'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='sent_from_shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_sent_from_shop', to='users.branch'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='sent_to_shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_sent_to_shop', to='users.branch'),
        ),
        migrations.AlterField(
            model_name='package',
            name='sent_from_shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_sent_from_shop', to='users.branch'),
        ),
        migrations.AlterField(
            model_name='package',
            name='sent_to_shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_sent_to_shop', to='users.branch'),
        ),
    ]
