# Generated by Django 6.0.6 on 2026-06-11 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='sent_from_shop',
        ),
        migrations.RemoveField(
            model_name='package',
            name='sent_to_shop',
        ),
        migrations.AlterField(
            model_name='package',
            name='logged_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logged_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
