# Generated by Django 6.0.6 on 2026-06-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_remove_package_sent_from_shop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
