# Generated by Django 6.0.6 on 2026-06-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_alter_package_added_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='collected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
