"""
Django settings for Movo project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env for local development
ENV_PATH = BASE_DIR / ".env"
if ENV_PATH.exists():
    for line in ENV_PATH.read_text().splitlines():
        if not line or line.strip().startswith("#"):
            continue
        if "=" not in line:
            continue
        key, value = line.split("=", 1)
        os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-&0(kf@(d@8piy=dijxhn=z#+_$q=))mu48cius#sd6g9+@#h&y"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "1") == "1"

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1,0.0.0.0").split(
    ","
)


# Application definition

INSTALLED_APPS = [
    #! Django default apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    #! Third-party apps
    "drf_spectacular",
    "rest_framework",
    "rest_framework_simplejwt",
    "corsheaders",
    #! Local apps
    "apps.users.apps.UsersConfig",
    "apps.intercity.apps.IntercityConfig",
    "apps.intracity.apps.IntracityConfig",
    "apps.bookkeeping.apps.BookkeepingConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "corsheaders.middleware.CorsMiddleware",
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # Next.js dev server
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Movo API",
    "DESCRIPTION": "API documentation for Movo services.",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),  # default is 5 minutes
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),  # default is 1 day
}

ROOT_URLCONF = "Movo.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "Movo.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if os.environ.get("DB_HOST"):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("DB_NAME", "movo_db"),
            "USER": os.environ.get("DB_USER", "movo_user"),
            "PASSWORD": os.environ.get("DB_PASSWORD", "movo_password"),
            "HOST": os.environ.get("DB_HOST", "db"),
            "PORT": os.environ.get("DB_PORT", "5432"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

ECOCASH_BASE_URL = os.environ.get(
    "ECOCASH_BASE_URL", "https://developers.ecocash.co.zw/sandbox"
)
ECOCASH_PAYMENT_URL = f"{ECOCASH_BASE_URL}/payment/v1/transactions/amount/"
ECOCASH_AUTH_HEADER = os.environ.get("ECOCASH_AUTH_HEADER")
ECOCASH_MERCHANT_CODE = os.environ.get("ECOCASH_MERCHANT_CODE", "287164")
ECOCASH_MERCHANT_PIN = os.environ.get("ECOCASH_MERCHANT_PIN", "1234")
ECOCASH_MERCHANT_NUMBER = os.environ.get("ECOCASH_MERCHANT_NUMBER", "778503033")
ECOCASH_TERMINAL_ID = os.environ.get("ECOCASH_TERMINAL_ID", "TERM001")
ECOCASH_LOCATION = os.environ.get("ECOCASH_LOCATION", "Harare")
ECOCASH_SUPER_MERCHANT_NAME = os.environ.get(
    "ECOCASH_SUPER_MERCHANT_NAME", "EcoCash Sandbox"
)
ECOCASH_MERCHANT_NAME = os.environ.get("ECOCASH_MERCHANT_NAME", "Test Merchant")
ECOCASH_NOTIFY_URL = os.environ.get(
    "ECOCASH_NOTIFY_URL", "https://myapp.example.com/webhook/eip"
)
