"""
Django settings for Movo project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path
from urllib.parse import quote

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env for local development
ENV_PATH = BASE_DIR / ".env"
if ENV_PATH.exists():
    for line in ENV_PATH.read_text().splitlines():
        if not line or line.strip().startswith("#"):
            continue
        if "=" not in line:
            continue
        key, value = line.split("=", 1)
        os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-&0(kf@(d@8piy=dijxhn=z#+_$q=))mu48cius#sd6g9+@#h&y",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "1") == "1"

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1,0.0.0.0").split(
        ","
    )
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    #! Django default apps
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    #! Third-party apps
    "drf_spectacular",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "channels",
    "corsheaders",
    #! Local apps
    "apps.users.apps.UsersConfig",
    "apps.intercity.apps.IntercityConfig",
    "apps.intracity.apps.IntracityConfig",
    "apps.bookkeeping.apps.BookkeepingConfig",
    "apps.transporters.apps.TransportersConfig",
    "apps.health.apps.HealthConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "corsheaders.middleware.CorsMiddleware",
]

ASGI_APPLICATION = "Movo.asgi.application"

CSRF_TRUSTED_ORIGINS = [
    "https://movobackend01-ccehf3gqbedmg6ax.southafricanorth-01.azurewebsites.net",
    "https://movo.co.zw",
]

CORS_ALLOWED_ORIGINS = [
    "https://movobackend01-ccehf3gqbedmg6ax.southafricanorth-01.azurewebsites.net",
    "https://movo.co.zw",
    "http://localhost:3000",
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Movo API",
    "DESCRIPTION": "API documentation for Movo services.",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),  # default is 5 minutes
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),  # default is 1 day
}

ROOT_URLCONF = "Movo.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "Movo.wsgi.application"
ASGI_APPLICATION = "Movo.asgi.application"

# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels.layers.InMemoryChannelLayer",
#     }
# }

USE_INMEMORY_CHANNEL_LAYER = (
    os.environ.get("USE_INMEMORY_CHANNEL_LAYER", "0") == "1"
)

CHANNEL_REDIS_HOST = os.environ.get("CHANNEL_REDIS_HOST", "127.0.0.1")
CHANNEL_REDIS_PORT = int(os.environ.get("CHANNEL_REDIS_PORT", "6379"))


def _build_channel_redis_url() -> str:
    # Prefer explicit URL-style variables often used in cloud deployments.
    explicit_url = (
        os.environ.get("CHANNEL_REDIS_URL")
        or os.environ.get("REDIS_URL")
        or os.environ.get("AZURE_REDIS_URL")
    )
    if explicit_url:
        return explicit_url

    # Support Azure Cache connection string format:
    # host:port,password=...,ssl=True,abortConnect=False
    azure_conn = os.environ.get("AZURE_REDIS_CONNECTIONSTRING", "").strip()
    if azure_conn and "://" not in azure_conn:
        parts = [part.strip() for part in azure_conn.split(",") if part.strip()]
        host_port = parts[0]
        options = {}
        for part in parts[1:]:
            if "=" not in part:
                continue
            key, value = part.split("=", 1)
            options[key.strip().lower()] = value.strip()

        password = options.get("password", "")
        ssl_enabled = options.get("ssl", "").lower() == "true"
        scheme = "rediss" if ssl_enabled else "redis"
        auth_segment = f":{quote(password, safe='')}@" if password else ""
        return f"{scheme}://{auth_segment}{host_port}/0"

    return f"redis://{CHANNEL_REDIS_HOST}:{CHANNEL_REDIS_PORT}/0"


CHANNEL_REDIS_URL = _build_channel_redis_url()
CHANNEL_REDIS_SOCKET_TIMEOUT = float(
    os.environ.get("CHANNEL_REDIS_SOCKET_TIMEOUT", "5")
)
CHANNEL_REDIS_SOCKET_CONNECT_TIMEOUT = float(
    os.environ.get("CHANNEL_REDIS_SOCKET_CONNECT_TIMEOUT", "5")
)
CHANNEL_REDIS_HEALTH_CHECK_INTERVAL = int(
    os.environ.get("CHANNEL_REDIS_HEALTH_CHECK_INTERVAL", "30")
)
CHANNEL_REDIS_RETRY_ON_TIMEOUT = (
    os.environ.get("CHANNEL_REDIS_RETRY_ON_TIMEOUT", "1") == "1"
)

AZURE_REDIS_CONN_STR = os.getenv("AZURE_REDIS_CONNECTIONSTRING")

if AZURE_REDIS_CONN_STR:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [AZURE_REDIS_CONN_STR],
            },
        },
    }
else:
    # Fallback for local Docker/development environment
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [("127.0.0.1", 6379)],
            },
        },
    }


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if os.environ.get("DB_HOST"):
    db_sslmode = os.environ.get("DB_SSLMODE")
    db_options = {"sslmode": db_sslmode} if db_sslmode else {}

    DATABASES = {
        "default": {
            "ENGINE": os.environ.get("DB_ENGINE", "django.db.backends.postgresql"),
            "NAME": os.environ.get("DB_NAME", "movo_db"),
            "USER": os.environ.get("DB_USER", "movo_user"),
            "PASSWORD": os.environ.get("DB_PASSWORD", "movo_password"),
            "HOST": os.environ.get("DB_HOST", "db"),
            "PORT": os.environ.get("DB_PORT", "5432"),
            "OPTIONS": db_options,
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"


TIME_ZONE = "Africa/Harare"
# TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_ROOT = BASE_DIR / "staticfiles"
STATIC_URL = "/static/"
STATIC_DIRS = [
    "staticfiles/admin",
    "staticfiles/rest_framework",
]

TXTCONSOLE_SEND_OTP = os.environ.get("TXTCONSOLE_SEND_OTP", "0") == "1"
TXTCONSOLE_BASE_URL = os.environ.get("TXTCONSOLE_BASE_URL", "https://api.txtconsole.com/v1")
TXTCONSOLE_SMS_URL = os.environ.get("TXTCONSOLE_SMS_URL")
TXTCONSOLE_SYSTEM_ID = os.environ.get("TXTCONSOLE_SYSTEM_ID")
TXTCONSOLE_PASSWORD = os.environ.get("TXTCONSOLE_PASSWORD")
TXTCONSOLE_SOURCE = os.environ.get("TXTCONSOLE_SOURCE")
TXTCONSOLE_RECEIPT_URL = os.environ.get("TXTCONSOLE_RECEIPT_URL")
TXTCONSOLE_SOURCE = os.environ.get("TXTCONSOLE_SOURCE", "MOVO")
TXTCONSOLE_AUTH_HEADER = os.environ.get("TXTCONSOLE_AUTH_HEADER")

# Paynow Integration Settings
PAYNOW_INTEGRATION_ID = os.environ.get("PAYNOW_INTEGRATION_ID")
PAYNOW_INTEGRATION_KEY = os.environ.get("PAYNOW_INTEGRATION_KEY")
