"""
Django settings for Movo project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path
from urllib.parse import quote, urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env for local development
ENV_PATH = BASE_DIR / ".env"
if ENV_PATH.exists():
    for line in ENV_PATH.read_text().splitlines():
        if not line or line.strip().startswith("#"):
            continue
        if "=" not in line:
            continue
        key, value = line.split("=", 1)
        os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-&0(kf@(d@8piy=dijxhn=z#+_$q=))mu48cius#sd6g9+@#h&y",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "1") == "1"

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1,0.0.0.0").split(
        ","
    )
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    #! Django default apps
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    #! Third-party apps
    "drf_spectacular",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "channels",
    "corsheaders",
    "storages",
    #! Local apps
    "apps.notifications.apps.NotificationsConfig",
    "apps.users.apps.UsersConfig",
    "apps.intercity.apps.IntercityConfig",
    "apps.intracity.apps.IntracityConfig",
    "apps.bookkeeping.apps.BookkeepingConfig",
    "apps.transporters.apps.TransportersConfig",
    "apps.adminportal.apps.AdminPortalConfig",
    "apps.health.apps.HealthConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ASGI_APPLICATION = "Movo.asgi.application"

CSRF_TRUSTED_ORIGINS = [
    "https://movo-backend-935754022035.europe-west1.run.app",
    "https://movo.co.zw",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

CORS_ALLOWED_ORIGINS = [
    "https://movo-backend-935754022035.europe-west1.run.app",
    "https://movo.co.zw",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Movo API",
    "DESCRIPTION": "API documentation for Movo services.",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),  # default is 5 minutes
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),  # default is 1 day
}

ROOT_URLCONF = "Movo.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "Movo.wsgi.application"
ASGI_APPLICATION = "Movo.asgi.application"

# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels.layers.InMemoryChannelLayer",
#     }
# }

USE_INMEMORY_CHANNEL_LAYER = (
    os.environ.get("USE_INMEMORY_CHANNEL_LAYER", "0") == "1"
)

CHANNEL_REDIS_HOST = os.environ.get("CHANNEL_REDIS_HOST", "127.0.0.1")
CHANNEL_REDIS_PORT = int(os.environ.get("CHANNEL_REDIS_PORT", "6379"))
CHANNEL_REDIS_USERNAME = os.environ.get("CHANNEL_REDIS_USERNAME", "")
CHANNEL_REDIS_PASSWORD = os.environ.get("CHANNEL_REDIS_PASSWORD", "")
CHANNEL_REDIS_DB = os.environ.get("CHANNEL_REDIS_DB", "0")
CHANNEL_REDIS_USE_SSL = os.environ.get("CHANNEL_REDIS_USE_SSL", "0") == "1"


def _build_channel_redis_url() -> str:
    # Prefer explicit URL-style variables often used in cloud deployments.
    explicit_url = (
        os.environ.get("CHANNEL_REDIS_URL")
        or os.environ.get("REDIS_URL")
        or os.environ.get("AZURE_REDIS_URL")
    )
    if explicit_url:
        return explicit_url

    # Support Azure Cache connection string format:
    # host:port,password=...,ssl=True,abortConnect=False
    azure_conn = os.environ.get("AZURE_REDIS_CONNECTIONSTRING", "").strip()
    if azure_conn and "://" not in azure_conn:
        parts = [part.strip() for part in azure_conn.split(",") if part.strip()]
        host_port = parts[0]
        options = {}
        for part in parts[1:]:
            if "=" not in part:
                continue
            key, value = part.split("=", 1)
            options[key.strip().lower()] = value.strip()

        password = options.get("password", "")
        ssl_enabled = options.get("ssl", "").lower() == "true"
        scheme = "rediss" if ssl_enabled else "redis"
        auth_segment = f":{quote(password, safe='')}@" if password else ""
        return f"{scheme}://{auth_segment}{host_port}/0"

    scheme = "rediss" if CHANNEL_REDIS_USE_SSL else "redis"
    username = quote(CHANNEL_REDIS_USERNAME, safe="") if CHANNEL_REDIS_USERNAME else ""
    password = quote(CHANNEL_REDIS_PASSWORD, safe="") if CHANNEL_REDIS_PASSWORD else ""
    if username and password:
        auth_segment = f"{username}:{password}@"
    elif password:
        auth_segment = f":{password}@"
    else:
        auth_segment = ""

    return f"{scheme}://{auth_segment}{CHANNEL_REDIS_HOST}:{CHANNEL_REDIS_PORT}/{CHANNEL_REDIS_DB}"


CHANNEL_REDIS_URL = _build_channel_redis_url()


def _build_celery_broker_url() -> str:
    """Return the explicit broker URL, or select the appropriate Redis service.

    Local Compose runs its own ``redis`` service. In production the web and
    worker processes must use the same managed Redis instance, so derive the
    Celery URL from the Redis credentials already used by Channels. Keeping an
    explicit ``CELERY_BROKER_URL`` as the first choice still supports a
    separately managed broker when one is deliberately configured.
    """
    explicit_url = os.environ.get("CELERY_BROKER_URL", "").strip()
    if explicit_url:
        return explicit_url

    if DEBUG:
        return "redis://redis:6379/1"

    host = os.environ.get("CELERY_REDIS_HOST", CHANNEL_REDIS_HOST)
    port = os.environ.get("CELERY_REDIS_PORT", str(CHANNEL_REDIS_PORT))
    username = os.environ.get("CELERY_REDIS_USERNAME", CHANNEL_REDIS_USERNAME)
    password = os.environ.get("CELERY_REDIS_PASSWORD", CHANNEL_REDIS_PASSWORD)
    database = os.environ.get("CELERY_REDIS_DB", CHANNEL_REDIS_DB)
    use_ssl = os.environ.get(
        "CELERY_REDIS_USE_SSL", "1" if CHANNEL_REDIS_USE_SSL else "0"
    ) == "1"

    encoded_username = quote(username, safe="") if username else ""
    encoded_password = quote(password, safe="") if password else ""
    if encoded_username and encoded_password:
        auth_segment = f"{encoded_username}:{encoded_password}@"
    elif encoded_password:
        auth_segment = f":{encoded_password}@"
    else:
        auth_segment = ""

    scheme = "rediss" if use_ssl else "redis"
    ssl_query = "?ssl_cert_reqs=required" if use_ssl else ""
    return f"{scheme}://{auth_segment}{host}:{port}/{database}{ssl_query}"


CELERY_BROKER_URL = _build_celery_broker_url()
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", CELERY_BROKER_URL)
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_TIME_LIMIT = 60

parsed_channel_redis = urlparse(CHANNEL_REDIS_URL)

CHANNEL_REDIS_SOCKET_TIMEOUT = float(
    os.environ.get("CHANNEL_REDIS_SOCKET_TIMEOUT", "60")
)
CHANNEL_REDIS_SOCKET_CONNECT_TIMEOUT = float(
    os.environ.get("CHANNEL_REDIS_SOCKET_CONNECT_TIMEOUT", "60")
)
CHANNEL_REDIS_HEALTH_CHECK_INTERVAL = int(
    os.environ.get("CHANNEL_REDIS_HEALTH_CHECK_INTERVAL", "30")
)
CHANNEL_REDIS_RETRY_ON_TIMEOUT = (
    os.environ.get("CHANNEL_REDIS_RETRY_ON_TIMEOUT", "1") == "1"
)

if USE_INMEMORY_CHANNEL_LAYER:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        },
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [
                    {
                        "address": CHANNEL_REDIS_URL,
                        "socket_timeout": CHANNEL_REDIS_SOCKET_TIMEOUT,
                        "socket_connect_timeout": CHANNEL_REDIS_SOCKET_CONNECT_TIMEOUT,
                        "retry_on_timeout": CHANNEL_REDIS_RETRY_ON_TIMEOUT,
                        "health_check_interval": CHANNEL_REDIS_HEALTH_CHECK_INTERVAL,
                    }
                ],
            },
        },
    }


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

db_sslmode = os.environ.get("DB_SSLMODE")
db_options = {"sslmode": db_sslmode} if db_sslmode else {}

DATABASES = {
    "default": {
        "ENGINE": os.environ.get("DB_ENGINE", "django.db.backends.postgresql"),
        "NAME": os.environ.get("DB_NAME", "movo_db"),
        "USER": os.environ.get("DB_USER", "movo_user"),
        "PASSWORD": os.environ.get("DB_PASSWORD", "movo_password"),
        "HOST": os.environ.get("DB_HOST", "db"),
        "PORT": os.environ.get("DB_PORT", "5432"),
        "OPTIONS": db_options,
    }
}


DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"


TIME_ZONE = "Africa/Harare"
# TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

if not DEBUG:
    DEFAULT_FILE_STORAGE = "storages.backends.azure_storage.AzureStorage"
    AZURE_ACCOUNT_NAME = os.environ.get("AZURE_ACCOUNT_NAME")
    AZURE_ACCOUNT_KEY = os.environ.get("AZURE_ACCOUNT_KEY")
    AZURE_CONTAINER = os.environ.get("AZURE_CONTAINER")

    STORAGES = {
        "default": {
            "BACKEND": "Movo.storage_backends.AzureMediaStorage",
            "OPTIONS": {
                "account_name": AZURE_ACCOUNT_NAME,
                "account_key": AZURE_ACCOUNT_KEY,
                "azure_container": AZURE_CONTAINER,
            },
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }

    MEDIA_URL = (
        f"https://{AZURE_ACCOUNT_NAME}.blob.core.windows.net/{AZURE_CONTAINER}/"
    )


STATIC_ROOT = BASE_DIR / "staticfiles"
STATIC_URL = "/static/"
STATIC_DIRS = [
    "staticfiles/admin",
    "staticfiles/rest_framework",
]

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

TXTCONSOLE_SEND_OTP = os.environ.get("TXTCONSOLE_SEND_OTP", "0") == "1"
TXTCONSOLE_BASE_URL = os.environ.get("TXTCONSOLE_BASE_URL", "https://api.txtconsole.com/v1")
TXTCONSOLE_SMS_URL = os.environ.get("TXTCONSOLE_SMS_URL")
TXTCONSOLE_SYSTEM_ID = os.environ.get("TXTCONSOLE_SYSTEM_ID")
TXTCONSOLE_PASSWORD = os.environ.get("TXTCONSOLE_PASSWORD")
TXTCONSOLE_SOURCE = os.environ.get("TXTCONSOLE_SOURCE")
TXTCONSOLE_RECEIPT_URL = os.environ.get("TXTCONSOLE_RECEIPT_URL")
TXTCONSOLE_SOURCE = os.environ.get("TXTCONSOLE_SOURCE", "MOVO")
TXTCONSOLE_AUTH_HEADER = os.environ.get("TXTCONSOLE_AUTH_HEADER")

# Paynow Integration Settings
PAYNOW_INTEGRATION_ID = os.environ.get("PAYNOW_INTEGRATION_ID")
PAYNOW_INTEGRATION_KEY = os.environ.get("PAYNOW_INTEGRATION_KEY")
