# Generated by Django 5.2.17 on 2026-09-13 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0003_rename_expensetype_expenseaccount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundstransfer',
            name='added_by',
        ),
        migrations.AddField(
            model_name='fundstransfer',
            name='accepted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_accepted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fundstransfer',
            name='initiated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
