# Generated by Django 5.2.17 on 2026-10-02 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0005_expense_is_reversed_expense_reason_for_reversal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intercitysale',
            name='account',
        ),
        migrations.RemoveField(
            model_name='intercitysale',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='intercitysale',
            name='intercity_invoice',
        ),
        migrations.RemoveField(
            model_name='transportexpense',
            name='Batch',
        ),
        migrations.RemoveField(
            model_name='transportexpense',
            name='account',
        ),
        migrations.RemoveField(
            model_name='transportexpense',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='transportexpense',
            name='expense_type',
        ),
        migrations.RemoveField(
            model_name='transportexpensereceipt',
            name='transport_expense',
        ),
        migrations.RenameField(
            model_name='charge',
            old_name='comment',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='comment',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='fundstransfer',
            old_name='comment',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='sale',
            new_name='expense',
        ),
        migrations.AddField(
            model_name='intracitysale',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('running_balance', models.FloatField(default=0)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('updated_at', models.DateField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookkeeping.account')),
            ],
        ),
        migrations.AddField(
            model_name='charge',
            name='running_balance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookkeeping.accountbalance'),
        ),
        migrations.AddField(
            model_name='expense',
            name='running_balance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookkeeping.accountbalance'),
        ),
        migrations.AddField(
            model_name='fundstransfer',
            name='from_account_running_balance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_account_running_balance', to='bookkeeping.accountbalance'),
        ),
        migrations.AddField(
            model_name='fundstransfer',
            name='to_account_running_balance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_account_running_balance', to='bookkeeping.accountbalance'),
        ),
        migrations.AddField(
            model_name='intracitysale',
            name='running_balance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookkeeping.accountbalance'),
        ),
        migrations.DeleteModel(
            name='ExpenseReceipt',
        ),
        migrations.DeleteModel(
            name='InterCitySale',
        ),
        migrations.DeleteModel(
            name='TransportExpense',
        ),
        migrations.DeleteModel(
            name='TransportExpenseReceipt',
        ),
    ]
