# Generated by Django 5.2.17 on 2026-10-02 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0006_remove_intercitysale_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='is_reversed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='charge',
            name='reason_for_reversal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charge',
            name='reversed_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charge',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charge_reversed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fundstransfer',
            name='is_reversed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fundstransfer',
            name='reason_for_reversal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundstransfer',
            name='reversed_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundstransfer',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_reversed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='charge',
            name='running_balance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookkeeping.accountbalance'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='running_balance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookkeeping.accountbalance'),
        ),
        migrations.AlterField(
            model_name='fundstransfer',
            name='from_account_running_balance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_account_running_balance', to='bookkeeping.accountbalance'),
        ),
        migrations.AlterField(
            model_name='fundstransfer',
            name='to_account_running_balance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_account_running_balance', to='bookkeeping.accountbalance'),
        ),
    ]
