# Generated by Django 5.2.17 on 2026-10-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0007_charge_is_reversed_charge_reason_for_reversal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundstransfer',
            old_name='accepted_by',
            new_name='approved_by',
        ),
        migrations.AddField(
            model_name='expense',
            name='supplier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
