# Generated by Django 5.2.17 on 2026-10-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0008_rename_accepted_by_fundstransfer_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fundstransfer',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='intracitysale',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
